### Задание 1
Найдите любую мультиязычную модель для `SentenceTransformers`, поддерживающую русский и английский языки, например, используйте [huggingface](https://huggingface.co/models?library=sentence-transformers). 

Используйте найденную модель для выравнивания предложений. Реализуйте функцию `get_sim_matrix`, которая будет возвращаться оценку семантической близости пар предложений (чем ближе по смыслу предложения, тем выше оценка).

In [22]:
import numpy as np
from scipy.spatial.distance import cosine
from sentence_transformers import SentenceTransformer
model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
model_st = SentenceTransformer(model_name)

src = """Ветер свистел над стенами Винтерфелла, заставляя знамена домов дрожать в преддверии заката. Джон Сноу стоял на бастионе, наблюдая за тёмными лесами, где тени деревьев казались живыми. Он чувствовал надвигающуюся опасность, словно невидимые шаги Белых ходоков приближались к стенам крепости."""
trg = """The wind whistled over the walls of Winterfell, making the banners of the houses flutter in the approaching dusk. Jon Snow stood on the battlement, watching the dark forests where the shadows of the trees seemed alive. He felt the impending danger, as if the invisible footsteps of the White Walkers were drawing closer to the castle walls."""

srcs = src.split(".")
trgs = trg.split(".")

src_embeds = model_st.encode(srcs)
trg_embeds = model_st.encode(trgs)


def get_sim_matrix(a, b):
    sim_matrix = np.zeros((len(a), len(b)))
    for i in range(len(a)):
        for j in range(len(b)):
            sim = 1 - cosine(a[i], b[j])
            sim_matrix[i,j] = sim
    return sim_matrix


sim_matrix = get_sim_matrix(src_embeds, trg_embeds)

# проверяем результат
np.testing.assert_array_equal(sim_matrix.argmax(1), np.arange(len(src_embeds)))

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6539.84it/s]


In [23]:
print(sim_matrix)

[[0.79106528 0.19875515 0.28958428 0.20363706]
 [0.45843744 0.88412255 0.39029813 0.12687808]
 [0.37455249 0.41850483 0.92576754 0.10795593]
 [0.19453311 0.12672836 0.06466669 1.        ]]
